version: '3'
services:
  db:
    build: ./db
    ports:
    - "127.0.0.1:5432:5432"
    volumes:
    - /var/lib/postgres
  app:
    build: ./app
    depends_on:
    - db
    links:
    - db
    ports:
    - "127.0.0.1:8000:8000"
